version: 0.2
phases:
  pre_build:
    commands:
      - yarn
      - npm install --save-dev jest jest-environment-webdriver babel-jest regenerator-runtime chromedriver selenium-webdriver
      - yarn test
  build:
   commands:
      - yarn build --prod

reports:
    jest_reports:
        files:
            - junit.xml
        file-format: JUNITXML
        base-directory: .test

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build


