import "regenerator-runtime/runtime.js";
// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const chrome = require('selenium-webdriver/chrome');
const path = require('chromedriver').path;

const screen = {
  width: 640,
  height: 480
};

const service = new chrome.ServiceBuilder(path).build();
chrome.setDefaultService(service);

describe('addATask', function() {
  jest.setTimeout(30000)
  let driver
  let vars
  
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').setChromeOptions(new chrome.Options().headless().windowSize(screen)).build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('addATask', async function() {
    await driver.get("http://codebuildmspr2cicd.s3-website.eu-west-3.amazonaws.com/")
    await driver.manage().window().setRect(1600, 900)
    await driver.findElement(By.css(".form-control")).sendKeys("Learn Selenium")
    await driver.findElement(By.css(".form-control")).sendKeys(Key.ENTER)
    assert(await driver.findElement(By.css("li.todo-item:nth-last-child(1) label")).getText() == "Learn Selenium")
  })
})
