import "regenerator-runtime/runtime.js";
// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const chrome = require('selenium-webdriver/chrome');
const path = require('chromedriver').path;

const screen = {
  width: 640,
  height: 480
};

const service = new chrome.ServiceBuilder(path).build();
chrome.setDefaultService(service);

describe('CompletTest', function() {

  let driver
  let vars
  
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').setChromeOptions(new chrome.Options().headless().windowSize(screen)).build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CompletTest', async function() {
    await driver.get("http://codebuildmspr2cicd.s3-website.eu-west-3.amazonaws.com/")
    await driver.manage().window().setRect(945, 954)
    await driver.findElement(By.css(".todo-item:nth-child(1) input")).click()
    await driver.findElement(By.css(".todo-item:nth-child(2) input")).click()
    await driver.findElement(By.linkText("Completed")).click()
    assert(await driver.findElement(By.css(".todo-item:nth-child(2) label")).getText() == "Learn React")
    assert(await driver.findElement(By.css(".todo-item:nth-child(1) label")).getText() == "Learn Javascript")
  })
})